#!/usr/bin/env python

"""Executable to run lineage assignment routine

Extensively uses :class:`track.Lineage`
"""

from lineage_lib import track
import logging
import sys


def main():
    p_ref = None
    if len(sys.argv) > 1:
        try:
            p_ref = int(sys.argv[1])
        except:
            pass

    L = track.Lineage()
    if not L.lineages:
        L.guess_lineage()
    L.interactive_track(p_ref)

if __name__ == "__main__":
    logging.basicConfig(
        format="[%(asctime)s] %(levelname) 10s: %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        level=logging.INFO
    )
    main()
